name: Build Rust Release

on:
  pull_request:
    paths:
      - '**/*.rs'
      - 'Cargo.toml'
      - 'src/main.rs'
  push:
    branches:
      - main
    paths:
      - '**/*.rs'
      - 'Cargo.toml'
      - 'src/main.rs'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build release binary
        run: |
          cargo build --release || { echo "Build failed"; exit 1; }
          if [ -f target/release/carch ]; then
              mkdir -p build  # Create build directory if it doesn't exist
              mv target/release/carch ./build/carch  # Move the binary to build directory
          else
              echo "Binary not found. Build may have failed."
              exit 1
          fi
          rm -rf target/release  # Optional: remove the target/release directory

      - name: List build artifacts
        run: ls ./build

      - name: Commit and push the build directory
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use the PAT secret
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add build/carch
          git commit -m "Update build directory with new binary" || echo "No changes to commit"
          # Push changes to the main branch using the PAT
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/harilvfs/carch.git HEAD:main || echo "Push failed. Check permissions."
